# Generated by Django 4.2.4 on 2023-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('passwordreset', 'passwordreset')], default='email', max_length=128),
        ),
    ]
